@startuml "location-application"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddElementTag("micro_service", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="black", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="black")

title Component diagram for Location Application

Container(customer_app, "Customer Application", "Java, Spring Boot", "app", $tags = "micro_service")
Container(store_app, "Store Application", "Java, Spring Boot", "app", $tags = "micro_service")
System_Ext(ingress_gateway, "API Gateway", "Istio Ingress Gateway")

Container_Boundary(location_app, "Location Application") {
    Component(query_adapter, "Location Query Adapter", "REST Handler Adapter", "handler")
    Component(location_search_adapter, "Location Search Adapter", "gRPC Adapter", "grpc")

    Component(location_service, "Location Search Service", "Spring Bean", "service")

    Component(location_repository, "Location Repository", "R2DBC Repository", "repository")
    ComponentDb(location_db, "Location Database", "MySQL", "data", $tags = "storage")

    Rel(query_adapter, location_service, "Uses", "call")
    Rel(location_search_adapter, location_service, "Uses", "call")

    Rel(location_service, location_repository, "Uses", "call")

    Rel_R(location_repository, location_db, "Reads from and writes to", "JDBC")
}

Rel(customer_app, location_search_adapter, "Uses", "gRPC")
Rel(store_app, location_search_adapter, "Uses", "gRPC")
Rel(ingress_gateway, query_adapter, "Uses", "HTTP")

@enduml
