@startuml "location-application"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddElementTag("micro_service", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="black", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="black")

title Component diagram for Location Application

Container(customer_app, "Customer Application", "Java, Spring Boot", "customer", $tags = "micro_service")
Container(store_app, "Store Application", "Java, Spring Boot", "store", $tags = "micro_service")
Container(staff_app, "Staff Application", "Java, Spring Boot", "staff", $tags = "micro_service")
System_Ext(ingress_gateway, "Ingress Gateway", "Istio Ingress Gateway")

Container_Boundary(location_app, "Location Application") {
    Component(command_handler, "Web Command Handler", "Rest Handler", "handler")
    Component(query_handler, "Web Query Handler", "Rest Handler", "handler")
    Component(grpc, "gRPC", "gRPC Adapter", "grpc")
    Component(location_service, "location Service", "Spring Bean", "service")
    Component(location_repository, "location Repository", "R2DBC Repository", "repository")
    ComponentDb(location_db, "location Database", "MySQL", "catalog", $tags = "storage")

    Rel(command_handler, location_service, "Uses", "call")
    Rel(query_handler, location_service, "Uses", "call")
    Rel(location_service, location_repository, "Uses", "call")
    Rel(grpc, location_service, "Uses", "call")
    Rel_R(location_repository, location_db, "Reads from and writes to", "JDBC")
}

Rel(customer_app, grpc, "Uses", "gRPC")
Rel(store_app, grpc, "Uses", "gRPC")
Rel(staff_app, grpc, "Uses", "gRPC")
Rel(ingress_gateway, command_handler, "Uses", "HTTP")
Rel(ingress_gateway, query_handler, "Uses", "HTTP")

SHOW_LEGEND()
@enduml
