@startuml "staff-application"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddElementTag("micro_service", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="black", $legendText="micro service\neight sided")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="black")

title Component diagram for Staff Application

Container(rental_app, "Rental Application", "Java, Spring Boot", "app", $tags = "micro_service")
Container(payment_app, "Payment Application", "Java, Spring Boot", "app", $tags = "micro_service")
Container(store_app, "Store Application", "Java, Spring Boot", "app", $tags = "micro_service")
System_Ext(ingress_gateway, "Ingress Gateway", "Istio Ingress Gateway")

Container(location_app, "Location Application", "Java, Spring Boot", "app", $tags = "micro_service")

Container_Boundary(staff_app, "Staff Application") {
    Component(command_adapter, "Staff Command Adapter", "REST Handler Adapter", "handler")
    Component(query_adapter, "Staff Query Adapter", "REST Handler Adapter", "handler")
    Component(staff_search_adapter, "Staff Search Adapter", "gRPC Adapter", "grpc")
    Component(location_search_adapter, "Location Search Adapter", "gRPC Adapter", "grpc")

    Component(staff_mgmt_service, "Staff Management Service", "Spring Bean", "service")
    Component(staff_search_service, "Staff Search Service", "Spring Bean", "service")
    Component(staff_repository, "Staff Repository", "R2DBC Repository", "repository")
    ComponentDb(staff_db, "Staff Database", "MySQL", "data", $tags = "storage")

    Rel(command_adapter, staff_mgmt_service, "Uses", "call")
    Rel(query_adapter, staff_search_service, "Uses", "call")
    Rel(staff_search_adapter, staff_search_service, "Uses", "call")

    Rel(staff_mgmt_service, staff_repository, "Uses", "call")
    Rel(staff_mgmt_service, location_search_adapter, "Uses", "call")
    Rel(staff_search_service, staff_repository, "Uses", "call")
    Rel(staff_search_service, location_search_adapter, "Uses", "call")

    Rel_R(staff_repository, staff_db, "Reads from and writes to", "JDBC")
}

Rel(rental_app, staff_search_adapter, "Uses", "gRPC")
Rel(payment_app, staff_search_adapter, "Uses", "gRPC")
Rel(store_app, staff_search_adapter, "Uses", "gRPC")
Rel(location_search_adapter, location_app, "Uses", "gRPC")
Rel(ingress_gateway, command_adapter, "Uses", "HTTP")
Rel(ingress_gateway, query_adapter, "Uses", "HTTP")

SHOW_LEGEND()
@enduml
