C4Container
    title Architecture Diagram for Sakila DVD Rental Store

    Person(manager, "Manager")

    System_Boundary(sakila, "Sakila System") {
        Container(catalogService, "Catalog Service")
        ContainerDb(catalogDb, "Catalog Database", "MySQL")
        Container(customerService, "Customer Service")
        ContainerDb(customerDb, "Customer Database", "MySQL")
        Container(paymentService, "Payment Service")
        ContainerDb(paymentDb, "Payment Database", "MySQL")
        Container(rentalService, "Rental Service")
        ContainerDb(rentalDb, "Rental Database", "MySQL")
        Container(staffService, "Staff Service")
        ContainerDb(staffDb, "Staff Database", "MySQL")
        Container(storeService, "Store Service")
        ContainerDb(storeDb, "Store Database", "MySQL")
        Container(locationService, "Location Service")
        ContainerDb(locationDb, "Location Database", "MySQL")
    }


    Rel(manager, catalogService, "manages")
    Rel(manager, customerService, "manages")
    Rel(manager, rentalService, "manages")
    Rel(manager, paymentService, "manages")
    Rel(manager, storeService, "manages")

    Rel(catalogService, catalogDb, "read/write")

    Rel(customerService, locationService, "uses")
    BiRel(customerService, paymentService, "uses")
    BiRel(customerService, rentalService, "uses")
    BiRel(customerService, storeService, "uses")
    Rel(customerService, customerDb, "read/write")

    BiRel(locationService, staffService, "uses")
    BiRel(locationService, storeService, "uses")
    Rel(locationService, locationDb, "read/write")

    BiRel(paymentService, rentalService, "uses")
    BiRel(paymentService, staffService, "uses")
    Rel(paymentService, paymentDb, "read/write")

    BiRel(rentalService, staffService, "uses")
    Rel(rentalService, rentalDb, "read/write")

    BiRel(staffService, storeService, "uses")
    Rel(staffService, staffDb, "read/write")

    Rel(storeService, catalogService, "uses")
    Rel(storeService, storeDb, "read/write")

    UpdateLayoutConfig($c4ShapeInRow="4")
