server:
  port: 8080

spring:
  r2dbc:
    pool:
      initial-size: 10
      max-size: 10
    url: r2dbc:mysql://localhost:3306/sakila
    username: root
    password: example
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: example
      authentication-database: admin
  ### axon-mongo
  mongo:
    database-name: axon
    token-store:
      enabled: true
    saga-store:
      enabled: false
    event-store:
      enabled: true

axon:
  axonserver:
    enabled: false

  serializer:
    events: jackson
    messages: jackson
    general: jackson

  kafka:
    bootstrap-servers: localhost:9092
    client-id: kafka-axon-example
    default-topic: local-event
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: transactional

    producer:
      transaction-id-prefix: kafka-sample
      acks: all
      retries: 3
      event-processor-mode: subscribing

    fetcher:
      poll-timeout: 3000

    consumer:
      enable-auto-commit: true
      auto-commit-interval: 3000
      event-processor-mode: tracking

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
    jmx:
      exposure:
        exclude: "*"
